In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/sales.csv")

In [4]:
df

,order_id,order_date,customer,product,category,price,quantity,city,payment_method
0,1001,2026-01-05,Ravi,Laptop,Electronics,60000,1,Hyderabad,UPI
1,1002,2026-01-07,Priya,Mouse,Electronics,800,2,Bangalore,Card
2,1003,2026-01-10,Arjun,Keyboard,Electronics,1500,1,Chennai,UPI
3,1004,2026-01-12,Sneha,Monitor,Electronics,12000,2,Hyderabad,Card
4,1005,2026-01-15,Ravi,Headphones,Electronics,2500,1,Mumbai,UPI
5,1006,2026-01-18,Priya,Laptop,Electronics,60000,1,Bangalore,Card
6,1007,2026-01-20,Arjun,Mouse,Electronics,800,3,Chennai,Cash
7,1008,2026-01-22,Sneha,Keyboard,Electronics,1500,2,Hyderabad,UPI
8,1009,2026-01-25,Ravi,Monitor,Electronics,12000,1,Mumbai,Card
9,1010,2026-01-28,Priya,Headphones,Electronics,2500,2,Bangalore,UPI

In [5]:
df.head()

,order_id,order_date,customer,product,category,price,quantity,city,payment_method
0,1001,2026-01-05,Ravi,Laptop,Electronics,60000,1,Hyderabad,UPI
1,1002,2026-01-07,Priya,Mouse,Electronics,800,2,Bangalore,Card
2,1003,2026-01-10,Arjun,Keyboard,Electronics,1500,1,Chennai,UPI
3,1004,2026-01-12,Sneha,Monitor,Electronics,12000,2,Hyderabad,Card
4,1005,2026-01-15,Ravi,Headphones,Electronics,2500,1,Mumbai,UPI

In [7]:
df.tail()

,order_id,order_date,customer,product,category,price,quantity,city,payment_method
5,1006,2026-01-18,Priya,Laptop,Electronics,60000,1,Bangalore,Card
6,1007,2026-01-20,Arjun,Mouse,Electronics,800,3,Chennai,Cash
7,1008,2026-01-22,Sneha,Keyboard,Electronics,1500,2,Hyderabad,UPI
8,1009,2026-01-25,Ravi,Monitor,Electronics,12000,1,Mumbai,Card
9,1010,2026-01-28,Priya,Headphones,Electronics,2500,2,Bangalore,UPI

In [9]:
df.shape

(10, 9)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        10 non-null     int64
 1   order_date      10 non-null     str
 2   customer        10 non-null     str
 3   product         10 non-null     str
 4   category        10 non-null     str
 5   price           10 non-null     int64
 6   quantity        10 non-null     int64
 7   city            10 non-null     str
 8   payment_method  10 non-null     str
dtypes: int64(3), str(6)
memory usage: 848.0 bytes

In [11]:
df.describe()

         order_id         price   quantity
count    10.00000     10.000000  10.000000
mean   1005.50000  15360.000000   1.600000
std       3.02765  23914.161309   0.699206
min    1001.00000    800.000000   1.000000
25%    1003.25000   1500.000000   1.000000
50%    1005.50000   2500.000000   1.500000
75%    1007.75000  12000.000000   2.000000
max    1010.00000  60000.000000   3.000000

In [14]:
len(df)

10

In [15]:
df["price"].mean()

np.float64(15360.0)

In [16]:
df["price"].max()

np.int64(60000)

In [17]:
df["product"]

0        Laptop
1         Mouse
2      Keyboard
3       Monitor
4    Headphones
5        Laptop
6         Mouse
7      Keyboard
8       Monitor
9    Headphones
Name: product, dtype: str

In [18]:
products=df["product"]
print(products)

0        Laptop
1         Mouse
2      Keyboard
3       Monitor
4    Headphones
5        Laptop
6         Mouse
7      Keyboard
8       Monitor
9    Headphones
Name: product, dtype: str

In [20]:
df[["product","price","customer"]]

      product  price customer
0      Laptop  60000     Ravi
1       Mouse    800    Priya
2    Keyboard   1500    Arjun
3     Monitor  12000    Sneha
4  Headphones   2500     Ravi
5      Laptop  60000    Priya
6       Mouse    800    Arjun
7    Keyboard   1500    Sneha
8     Monitor  12000     Ravi
9  Headphones   2500    Priya

In [21]:
df.iloc[8]

order_id                 1009
order_date         2026-01-25
customer                 Ravi
product               Monitor
category          Electronics
price                   12000
quantity                    1
city                   Mumbai
payment_method           Card
Name: 8, dtype: object

In [22]:
df.iloc[2:6]

,order_id,order_date,customer,product,category,price,quantity,city,payment_method
2,1003,2026-01-10,Arjun,Keyboard,Electronics,1500,1,Chennai,UPI
3,1004,2026-01-12,Sneha,Monitor,Electronics,12000,2,Hyderabad,Card
4,1005,2026-01-15,Ravi,Headphones,Electronics,2500,1,Mumbai,UPI
5,1006,2026-01-18,Priya,Laptop,Electronics,60000,1,Bangalore,Card

In [23]:
df.iloc[2,4]

'Electronics'

In [24]:
df.iloc[2:4,2:4]

  customer   product
2    Arjun  Keyboard
3    Sneha   Monitor

In [25]:
df[["customer","city"]]

  customer       city
0     Ravi  Hyderabad
1    Priya  Bangalore
2    Arjun    Chennai
3    Sneha  Hyderabad
4     Ravi     Mumbai
5    Priya  Bangalore
6    Arjun    Chennai
7    Sneha  Hyderabad
8     Ravi     Mumbai
9    Priya  Bangalore

In [26]:
df.iloc[0:6]

,order_id,order_date,customer,product,category,price,quantity,city,payment_method
0,1001,2026-01-05,Ravi,Laptop,Electronics,60000,1,Hyderabad,UPI
1,1002,2026-01-07,Priya,Mouse,Electronics,800,2,Bangalore,Card
2,1003,2026-01-10,Arjun,Keyboard,Electronics,1500,1,Chennai,UPI
3,1004,2026-01-12,Sneha,Monitor,Electronics,12000,2,Hyderabad,Card
4,1005,2026-01-15,Ravi,Headphones,Electronics,2500,1,Mumbai,UPI
5,1006,2026-01-18,Priya,Laptop,Electronics,60000,1,Bangalore,Card

In [27]:
df.iloc[5,3]

'Laptop'

In [28]:
df.iloc[0:4,[3,5,6]]

    product  price  quantity
0    Laptop  60000         1
1     Mouse    800         2
2  Keyboard   1500         1
3   Monitor  12000         2

In [31]:
df[df["product"] == "Laptop"]

,order_id,order_date,customer,product,category,price,quantity,city,payment_method
0,1001,2026-01-05,Ravi,Laptop,Electronics,60000,1,Hyderabad,UPI
5,1006,2026-01-18,Priya,Laptop,Electronics,60000,1,Bangalore,Card

In [32]:
df["price"]>10000

0     True
1    False
2    False
3     True
4    False
5     True
6    False
7    False
8     True
9    False
Name: price, dtype: bool

In [34]:
df[df["price"]>10000]

,order_id,order_date,customer,product,category,price,quantity,city,payment_method
0,1001,2026-01-05,Ravi,Laptop,Electronics,60000,1,Hyderabad,UPI
3,1004,2026-01-12,Sneha,Monitor,Electronics,12000,2,Hyderabad,Card
5,1006,2026-01-18,Priya,Laptop,Electronics,60000,1,Bangalore,Card
8,1009,2026-01-25,Ravi,Monitor,Electronics,12000,1,Mumbai,Card

In [35]:
df[df["city"]=="Mumbai"]

,order_id,order_date,customer,product,category,price,quantity,city,payment_method
4,1005,2026-01-15,Ravi,Headphones,Electronics,2500,1,Mumbai,UPI
8,1009,2026-01-25,Ravi,Monitor,Electronics,12000,1,Mumbai,Card

In [ ]:
df[df["city"]=="Mumbai"][["customer","product"]]

  customer     product
4     Ravi  Headphones
8     Ravi     Monitor

In [38]:
df[(df["city"]=="Mumbai") & (df["price"]>10000)]

,order_id,order_date,customer,product,category,price,quantity,city,payment_method
8,1009,2026-01-25,Ravi,Monitor,Electronics,12000,1,Mumbai,Card

In [39]:
df[(df["city"]=="Mumbai") | (df["price"]>10000)]

,order_id,order_date,customer,product,category,price,quantity,city,payment_method
0,1001,2026-01-05,Ravi,Laptop,Electronics,60000,1,Hyderabad,UPI
3,1004,2026-01-12,Sneha,Monitor,Electronics,12000,2,Hyderabad,Card
4,1005,2026-01-15,Ravi,Headphones,Electronics,2500,1,Mumbai,UPI
5,1006,2026-01-18,Priya,Laptop,Electronics,60000,1,Bangalore,Card
8,1009,2026-01-25,Ravi,Monitor,Electronics,12000,1,Mumbai,Card

In [40]:
df[df["quantity"]>=2]

,order_id,order_date,customer,product,category,price,quantity,city,payment_method
1,1002,2026-01-07,Priya,Mouse,Electronics,800,2,Bangalore,Card
3,1004,2026-01-12,Sneha,Monitor,Electronics,12000,2,Hyderabad,Card
6,1007,2026-01-20,Arjun,Mouse,Electronics,800,3,Chennai,Cash
7,1008,2026-01-22,Sneha,Keyboard,Electronics,1500,2,Hyderabad,UPI
9,1010,2026-01-28,Priya,Headphones,Electronics,2500,2,Bangalore,UPI

In [41]:
df[df["price"]<5000][["customer","product","price"]]

  customer     product  price
1    Priya       Mouse    800
2    Arjun    Keyboard   1500
4     Ravi  Headphones   2500
6    Arjun       Mouse    800
7    Sneha    Keyboard   1500
9    Priya  Headphones   2500

In [42]:
df[df["city"] == "Bangalore"]

,order_id,order_date,customer,product,category,price,quantity,city,payment_method
1,1002,2026-01-07,Priya,Mouse,Electronics,800,2,Bangalore,Card
5,1006,2026-01-18,Priya,Laptop,Electronics,60000,1,Bangalore,Card
9,1010,2026-01-28,Priya,Headphones,Electronics,2500,2,Bangalore,UPI

In [43]:
df[(df["price"]>10000) & (df["quantity"]>=2)]

,order_id,order_date,customer,product,category,price,quantity,city,payment_method
3,1004,2026-01-12,Sneha,Monitor,Electronics,12000,2,Hyderabad,Card

In [44]:
df[(df["city"]=="Hyderabad") | (df["city"]=="Chennai")]

,order_id,order_date,customer,product,category,price,quantity,city,payment_method
0,1001,2026-01-05,Ravi,Laptop,Electronics,60000,1,Hyderabad,UPI
2,1003,2026-01-10,Arjun,Keyboard,Electronics,1500,1,Chennai,UPI
3,1004,2026-01-12,Sneha,Monitor,Electronics,12000,2,Hyderabad,Card
6,1007,2026-01-20,Arjun,Mouse,Electronics,800,3,Chennai,Cash
7,1008,2026-01-22,Sneha,Keyboard,Electronics,1500,2,Hyderabad,UPI

In [45]:
df[df["quantity"]>=2][["product","price","quantity"]]

      product  price  quantity
1       Mouse    800         2
3     Monitor  12000         2
6       Mouse    800         3
7    Keyboard   1500         2
9  Headphones   2500         2

In [46]:
df["revenue"] = df["quantity"] * df["price"]

In [47]:
df

,order_id,order_date,customer,product,category,price,quantity,city,payment_method,revenue
0,1001,2026-01-05,Ravi,Laptop,Electronics,60000,1,Hyderabad,UPI,60000
1,1002,2026-01-07,Priya,Mouse,Electronics,800,2,Bangalore,Card,1600
2,1003,2026-01-10,Arjun,Keyboard,Electronics,1500,1,Chennai,UPI,1500
3,1004,2026-01-12,Sneha,Monitor,Electronics,12000,2,Hyderabad,Card,24000
4,1005,2026-01-15,Ravi,Headphones,Electronics,2500,1,Mumbai,UPI,2500
5,1006,2026-01-18,Priya,Laptop,Electronics,60000,1,Bangalore,Card,60000
6,1007,2026-01-20,Arjun,Mouse,Electronics,800,3,Chennai,Cash,2400
7,1008,2026-01-22,Sneha,Keyboard,Electronics,1500,2,Hyderabad,UPI,3000
8,1009,2026-01-25,Ravi,Monitor,Electronics,12000,1,Mumbai,Card,12000
9,1010,2026-01-28,Priya,Headphones,Electronics,2500,2,Bangalore,UPI,5000

In [48]:
df["revenue"].sum()

np.int64(172000)

In [52]:
df[df["revenue"] == df["revenue"].max()]

,order_id,order_date,customer,product,category,price,quantity,city,payment_method,revenue
0,1001,2026-01-05,Ravi,Laptop,Electronics,60000,1,Hyderabad,UPI,60000
5,1006,2026-01-18,Priya,Laptop,Electronics,60000,1,Bangalore,Card,60000

In [57]:
df.sort_values("price", ascending=False)

,order_id,order_date,customer,product,category,price,quantity,city,payment_method,revenue
0,1001,2026-01-05,Ravi,Laptop,Electronics,60000,1,Hyderabad,UPI,60000
5,1006,2026-01-18,Priya,Laptop,Electronics,60000,1,Bangalore,Card,60000
8,1009,2026-01-25,Ravi,Monitor,Electronics,12000,1,Mumbai,Card,12000
3,1004,2026-01-12,Sneha,Monitor,Electronics,12000,2,Hyderabad,Card,24000
9,1010,2026-01-28,Priya,Headphones,Electronics,2500,2,Bangalore,UPI,5000
4,1005,2026-01-15,Ravi,Headphones,Electronics,2500,1,Mumbai,UPI,2500
7,1008,2026-01-22,Sneha,Keyboard,Electronics,1500,2,Hyderabad,UPI,3000
2,1003,2026-01-10,Arjun,Keyboard,Electronics,1500,1,Chennai,UPI,1500
1,1002,2026-01-07,Priya,Mouse,Electronics,800,2,Bangalore,Card,1600
6,1007,2026-01-20,Arjun,Mouse,Electronics,800,3,Chennai,Cash,2400

In [58]:
df.sort_values("quantity")

,order_id,order_date,customer,product,category,price,quantity,city,payment_method,revenue
0,1001,2026-01-05,Ravi,Laptop,Electronics,60000,1,Hyderabad,UPI,60000
2,1003,2026-01-10,Arjun,Keyboard,Electronics,1500,1,Chennai,UPI,1500
5,1006,2026-01-18,Priya,Laptop,Electronics,60000,1,Bangalore,Card,60000
4,1005,2026-01-15,Ravi,Headphones,Electronics,2500,1,Mumbai,UPI,2500
8,1009,2026-01-25,Ravi,Monitor,Electronics,12000,1,Mumbai,Card,12000
3,1004,2026-01-12,Sneha,Monitor,Electronics,12000,2,Hyderabad,Card,24000
7,1008,2026-01-22,Sneha,Keyboard,Electronics,1500,2,Hyderabad,UPI,3000
1,1002,2026-01-07,Priya,Mouse,Electronics,800,2,Bangalore,Card,1600
9,1010,2026-01-28,Priya,Headphones,Electronics,2500,2,Bangalore,UPI,5000
6,1007,2026-01-20,Arjun,Mouse,Electronics,800,3,Chennai,Cash,2400

In [59]:
df.sort_values("revenue",ascending=False)[["customer","product","revenue"]]

  customer     product  revenue
0     Ravi      Laptop    60000
5    Priya      Laptop    60000
3    Sneha     Monitor    24000
8     Ravi     Monitor    12000
9    Priya  Headphones     5000
7    Sneha    Keyboard     3000
4     Ravi  Headphones     2500
6    Arjun       Mouse     2400
1    Priya       Mouse     1600
2    Arjun    Keyboard     1500

In [60]:
df.sort_values("revenue",ascending=False).head(3)

,order_id,order_date,customer,product,category,price,quantity,city,payment_method,revenue
0,1001,2026-01-05,Ravi,Laptop,Electronics,60000,1,Hyderabad,UPI,60000
5,1006,2026-01-18,Priya,Laptop,Electronics,60000,1,Bangalore,Card,60000
3,1004,2026-01-12,Sneha,Monitor,Electronics,12000,2,Hyderabad,Card,24000